### ISSUE TITLE
Excluding paths

### ISSUE THREAD

**Issue by andrewgy8** [Raekkeri/django-requestlogs#40]
Hey! Just about to use this on a project of mine. 

Is there a way to exclude paths? 

For example, I want to exclude logging all `/admin/*` requests.

**Comment by Raekkeri** [comment]
Hi, this kind of feature has been on my mind since the beginning, but couldn't yet decide on how to implement. Most straightforward would be to just add such option to settings, e.g. `'IGNORE_PATHS': ['/admin/']`, but should this support regex or some other (simpler) wildcard policy?

If you want to go forward with your own implementation though, you can just overwrite the `RequestLogEntry` class and implement your own `skip_entry(...)`, something like:

```
class MyRequestLogEntry(RequestLogEntry):
    def skip_entry(self):
        if super().skip_entry():
            return True
        if self.request.path.startswith('/admin'):
            return True
```

But I'll see about adding a built-in support fort this.

**Comment by andrewgy8** [comment]
One way to do this would be with a callback function. Something like 

```
def skip_admin_pages(path):
	return path.startswith('/admin')

...
'IGNORE_PATHS': skip_admin_pages,

....

class MyRequestLogEntry(RequestLogEntry):
    def skip_entry(self):
        if super().skip_entry():
            return True
        if settings.IGNORE_PATHS(self.request.path):
            return True
```

Not sure it can be implemented exactly like that but I think you get the drift Im going in 😉

**Comment by Raekkeri** [comment]
@andrewgy8 This is now supported in 0.7.0.
